### ISSUE TITLE
':DURATIVE-ACTIONS': domain definition expected

### ISSUE THREAD

**Issue by JINXER000** [jan-dolejsi/vscode-pddl-samples#1]
I am a novice and have been exploring your great job. When I run the planner in vscode, it always warn me like that ,`syntax error in line 8, ':DURATIVE-ACTIONS': domain definition expected
Planner found 0 plan(s) in 0.726secs.` How can I fix this issue?

Thanks.

**Comment by JINXER000** [comment]
> I am a novice and have been exploring your great job. When I run the planner in vscode, it always warn me like that ,`syntax error in line 8, ':DURATIVE-ACTIONS': domain definition expected Planner found 0 plan(s) in 0.726secs.` How can I fix this issue?
> 
> Thanks.

Sorry that I missed the comment below the Youtube video. But I am still confused how to set up the solver on my windows PC. Can anybody give me a brief instruction?

**Comment by jan-dolejsi** [comment]
The availability and accessibility of planner binaries is the hardest problem in the community. The planners are listed here https://planning.wiki/ref/planners and some of them detail how to download or compile them. The planning Slack community is best to get help with broad open-ended questions: https://join.slack.com/t/theplanningcommunity/shared_invite/enQtNjg0MTIzNTE3MTY4LTQ4YTRiNjhjNmVlNmEwMGMxOTQwNTZlYWM2YTk1YjdkZmIyMTU5MzRjZjYzOWYxMjJkNGM3YTM2MWI0MmM2MGY 

For specific issues with PDDL modeling or usage of a given planner, there is http://stackoverflow.com/tags/pddl

I will close this issue now and hope you can get help in the forums.
